package snake;

import java.awt.event.KeyEvent;

/**
 *
 * @author Tim Barber
 */
public class HighScore extends javax.swing.JPanel {

    /**
     * Creates new form HighScore
     */
    public HighScore() {
        initComponents();
        nameFieldMouseClicked(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ENTERYOURNAME = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        counter = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        ENTERYOURNAME.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        ENTERYOURNAME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ENTERYOURNAME.setText("ENTER YOUR NAME");

        nameField.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        nameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameFieldMouseClicked(evt);
            }
        });
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameFieldKeyReleased(evt);
            }
        });

        okButton.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        okButton.setText("OK");
        okButton.setEnabled(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        counter.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        counter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        counter.setText("30");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(nameField)
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ENTERYOURNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(counter, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ENTERYOURNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(counter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(okButton))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (nameField.getText().length() > 0) {
            Snake.setUserName(nameField.getText());
        }
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     *
     * @param i the number to set the time display to
     */
    public void setCounter(int i) {
        counter.setText(String.valueOf(i));
    }
    private void nameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            okButtonActionPerformed(null);
            return;
        }
        String old = nameField.getText().toUpperCase();
        String out = "";
        for (Character c : old.toCharArray()) {
            if (Character.isAlphabetic(c)) {
                out += c;
            }
        }
        if (out.length() > 3) {
            out = out.substring(0, 3);
        }
        nameField.setText(out);
        if (nameField.getText().length() == 3) {
            okButton.setEnabled(true);
        } else {
            okButton.setEnabled(false);

        }    }//GEN-LAST:event_nameFieldKeyPressed

    /**
     *
     * @return x-coordinate of the top left corner of the "name" text field
     */
    public int getFieldX() {
        return nameField.getX();
    }

    /**
     *
     * @return y-coordinate of the top left corner of the "name" text field
     */
    public int getFieldY() {
        return nameField.getY();
    }

    private void nameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyReleased
        // make the text upper case and trim it down to 3 characters
        nameField.setText(nameField.getText().toUpperCase().substring(0, (nameField.getText().length() < 3 ? nameField.getText().length() : 3)));

        // If there are three characters, we're good
        if (nameField.getText().length() == 3) {
            okButton.setEnabled(true);
        } else {
            okButton.setEnabled(false);

        }
    }//GEN-LAST:event_nameFieldKeyReleased

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void nameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameFieldMouseClicked

    }//GEN-LAST:event_nameFieldMouseClicked

    /**
     * Requests focus on the field
     */
    public void setFocusOnField() {
        nameField.requestFocus();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ENTERYOURNAME;
    private javax.swing.JLabel counter;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
